---

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 3.0


Metrics/BlockLength:
  Max: 100
  Exclude:
    - config/routes.rb
    - config/initializers/*
    - spec/**/*_spec.rb
    - spec/factories.rb
    - lib/tasks/*.rake

# metrics and documentation. code is complex as it needs to be,
# and docs shouldn't be required. add them when needed.
Metrics/AbcSize:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: false
Style/Documentation:
  Enabled: false

# differences from standard ruby style guide.
Style/RegexpLiteral:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/NumericPredicate:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
