source 'https://rubygems.org'
ruby '2.2.1'

gem 'oj'
gem 'rails', '4.2.0'
gem 'redis', require: %w[redis redis/connection/hiredis]
gem 'leveldb-ruby','0.15', require: 'leveldb'

group :development do
  gem 'spring'
  gem 'thin'
end

group :production do
  gem 'puma'
  gem 'rails_12factor'
  gem 'bugsnag'
end
