---
http_interactions:
- request:
    method: post
    uri: https://conda-parser.libraries.io/parse
    body:
      encoding: UTF-8
      string: file=name%3A%20testingenv%0Achannels%3A%0A%20%20-%20defaults%0Adependencies%3A%0A%20%20-%20pip%0A%20%20-%20pip%3A%0A%20%20%20%20%20%20-%20urllib3%0A%20%20%20%20%20%20-%20Django%3D%3D2.0.0%0A%20%20-%20sqlite%3D3.29.0%3Dh7b6447c_0%0A&filename=environment.yml
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Contenttype:
      - multipart/form-data
      Expect:
      - ''
  response:
    status:
      code: 200
      message: ''
    headers:
      Server:
      - gunicorn/19.9.0
      Date:
      - Tue, 11 May 2021 16:48:25 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '143'
      Via:
      - 1.1 google
      Alt-Svc:
      - clear
    body:
      encoding: ASCII-8BIT
      string: '{"bad_specs":[],"channels":["defaults"],"lockfile":null,"manifest":[{"name":"pip","requirement":""},{"name":"sqlite","requirement":"3.29.0"}]}

'
    http_version: null
  recorded_at: Tue, 11 May 2021 16:48:25 GMT
recorded_with: VCR 5.1.0
